language: python
arch:
  - amd64
  - ppc64le
python:
  - "3.6"
  - "3.7"

install:
  - pip install codecov pytest pytest-cov trollimage xarray dask[array]
  - pip install -e .

script:
  - pytest --cov=./

after_success:
  - codecov
